version: '3'
services:
    postgres:
        image: postgres
        restart: "unless-stopped"
        environment:
            - POSTGRES_USER=woofs
            - POSTGRES_PASSWORD=woofs
            - POSTGRES_DB=woofs
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        hostname: pgadmin4
        restart: "unless-stopped"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@woofs.com
            - PGADMIN_DEFAULT_PASSWORD=woofs
        depends_on:
            - postgres
        ports:
            - "18080:80"
    dbeaver:
      image: "dbeaver/cloudbeaver:latest"
      hostname: dbeaver
      restart: "unless-stopped"
      ports:
        - 8978:8978